name: Enterprise SDET Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
    #  retrive the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Install Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # installing technical requirements 
    - name: Install Dependencies
      run: |
        pip3 install pytest pytest-playwright pytest-html pytest-xdist requests
        playwright install chromium

    - name: Execute Tests
      run: pytest -n 3 --html=report.html --self-contained-html

    - name: Upload HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Automation-Dashboard
        path: report.html